[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
# solc = "0.6.12"
eth-rpc-url = "127.0.0.1:8545"  
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_TOKEN}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
